import type { Quote } from '@/types';

/** Ampliación de la colección de frases (clásicos, filosofía, literatura en español y ciencia). */
export const MORE_QUOTES: Quote[] = [
  // Estoicos
  { text: "La felicidad de tu vida depende de la calidad de tus pensamientos.", author: "Marco Aurelio", context: "Meditaciones, libro V.", meaning: "Lo que te repetís por dentro tiñe cómo vivís lo que pasa afuera." },
  { text: "Tienes poder sobre tu mente, no sobre los acontecimientos. Date cuenta de esto y encontrarás la fuerza.", author: "Marco Aurelio", context: "Meditaciones. Escritas durante campañas militares, sin intención de publicarse.", meaning: "Poner la energía donde sí hay control devuelve calma y eficacia." },
  { text: "Lo que no es bueno para la colmena no es bueno para la abeja.", author: "Marco Aurelio", context: "Meditaciones, libro VI.", meaning: "El bien propio y el común están más unidos de lo que parece." },
  { text: "La mejor venganza es no parecerse a quien te hizo daño.", author: "Marco Aurelio", context: "Meditaciones, libro VI.", meaning: "Responder al mal sin copiarlo es la forma más alta de no dejarse vencer." },
  { text: "Pronto habrás olvidado todo; pronto todos te habrán olvidado.", author: "Marco Aurelio", context: "Meditaciones, libro VII.", meaning: "Recordar la fugacidad baja el peso de la opinión ajena y del ego." },
  { text: "Sufrimos más a menudo en la imaginación que en la realidad.", author: "Séneca", context: "Cartas a Lucilio, carta 13.", meaning: "Gran parte del miedo es anticipación: lo temido casi nunca llega tal como lo imaginamos." },
  { text: "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.", author: "Séneca", context: "Idea atribuida a Séneca; la formulación moderna es una paráfrasis.", meaning: "Prepararse multiplica las chances de aprovechar lo inesperado." },
  { text: "Ningún viento es favorable para quien no sabe a qué puerto se dirige.", author: "Séneca", context: "Cartas a Lucilio, carta 71.", meaning: "Sin un rumbo, cualquier ayuda o impulso se desperdicia." },
  { text: "Apresúrate a vivir bien y piensa que cada día es por sí solo una vida.", author: "Séneca", context: "Cartas a Lucilio, carta 101.", meaning: "No postergar la vida buena para un futuro que no está garantizado." },
  { text: "No es pobre el que tiene poco, sino el que mucho desea.", author: "Séneca", context: "Cartas a Lucilio, carta 2.", meaning: "La riqueza también se mide por cuánto necesitás para estar en paz." },
  { text: "Es imposible que un hombre aprenda lo que cree que ya sabe.", author: "Epicteto", context: "Discursos, libro II.", meaning: "La humildad es la condición para aprender." },
  { text: "Ningún gran logro se consigue de repente.", author: "Epicteto", context: "Discursos, libro I: «ni siquiera un racimo de uvas o un higo».", meaning: "Lo valioso madura con tiempo y proceso." },
  { text: "La riqueza no consiste en tener grandes posesiones, sino en tener pocas necesidades.", author: "Epicteto", context: "Fragmento transmitido por Estobeo.", meaning: "Reducir lo que necesitás es otra forma de volverte rico." },

  // Filosofía clásica y moderna
  { text: "Solo sé que no sé nada.", author: "Sócrates", context: "Fórmula tradicional que resume la Apología de Platón.", meaning: "Reconocer la propia ignorancia es el inicio del conocimiento." },
  { text: "Somos lo que hacemos día a día; de modo que la excelencia no es un acto, sino un hábito.", author: "Aristóteles", context: "Versión popular de la Ética a Nicómaco, libro II.", meaning: "El carácter se forma con la repetición de pequeñas acciones." },
  { text: "Una golondrina no hace verano, ni un solo día.", author: "Aristóteles", context: "Ética a Nicómaco, libro I.", meaning: "La vida buena se juzga por su conjunto, no por un momento aislado." },
  { text: "Es la marca de una mente educada ser capaz de considerar un pensamiento sin aceptarlo.", author: "Aristóteles", context: "Paráfrasis moderna de la Ética a Nicómaco.", meaning: "Pensar bien incluye poder escuchar ideas sin adoptarlas." },
  { text: "Nadie se baña dos veces en el mismo río.", author: "Heráclito", context: "Fragmento transmitido por Platón en el Crátilo.", meaning: "Ni el río ni nosotros somos los mismos: todo cambia." },
  { text: "El carácter de un hombre es su destino.", author: "Heráclito", context: "Fragmento 119 (Diels-Kranz).", meaning: "Cómo somos va trazando lo que nos pasa." },
  { text: "No es rico el que tiene mucho, sino el que da mucho.", author: "Epicuro", context: "Pensamiento transmitido en sus máximas.", meaning: "La generosidad es una forma de abundancia." },
  { text: "De todos los bienes que la sabiduría procura para la felicidad de la vida entera, el más grande es la amistad.", author: "Epicuro", context: "Máximas capitales, XXVII.", meaning: "Los vínculos son el tesoro más firme." },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau", context: "Frase atribuida en su pensamiento pedagógico (siglo XVIII).", meaning: "Esperar cuesta, pero lo que madura con tiempo vale más." },
  { text: "Atrévete a saber.", author: "Immanuel Kant", context: "¿Qué es la Ilustración? (1784), retomando el «Sapere aude» de Horacio.", meaning: "Pensar por uno mismo requiere valentía." },
  { text: "Dos cosas llenan el ánimo de admiración: el cielo estrellado sobre mí y la ley moral dentro de mí.", author: "Immanuel Kant", context: "Crítica de la razón práctica (1788), conclusión.", meaning: "Asombrarse por el universo y por la conciencia propia." },
  { text: "El corazón tiene razones que la razón ignora.", author: "Blaise Pascal", context: "Pensamientos (1670).", meaning: "No todo lo importante se explica con lógica." },
  { text: "Toda la desgracia de los hombres viene de no saber quedarse tranquilos en una habitación.", author: "Blaise Pascal", context: "Pensamientos (1670), sobre la distracción.", meaning: "Huir del silencio y de uno mismo trae muchos problemas." },
  { text: "Lo que no me mata me hace más fuerte.", author: "Friedrich Nietzsche", context: "Crepúsculo de los ídolos (1889).", meaning: "Las dificultades atravesadas pueden volverse recursos." },
  { text: "Sin música, la vida sería un error.", author: "Friedrich Nietzsche", context: "Crepúsculo de los ídolos (1889).", meaning: "El arte no es un lujo: da sentido a la existencia." },
  { text: "Llega a ser el que eres.", author: "Friedrich Nietzsche", context: "Subtítulo de Ecce homo, tomado de Píndaro.", meaning: "La vida es un proceso de volverse uno mismo." },
  { text: "El hombre está condenado a ser libre.", author: "Jean-Paul Sartre", context: "El existencialismo es un humanismo (1946).", meaning: "No podemos evitar elegir; incluso no elegir es una elección." },
  { text: "En medio del invierno aprendí por fin que había en mí un verano invencible.", author: "Albert Camus", context: "Regreso a Tipasa (1952).", meaning: "Aun en las épocas oscuras hay en nosotros algo que resiste." },
  { text: "Hay que imaginarse a Sísifo feliz.", author: "Albert Camus", context: "El mito de Sísifo (1942), última línea.", meaning: "El sentido puede encontrarse en el propio esfuerzo, no solo en la meta." },
  { text: "Los límites de mi lenguaje significan los límites de mi mundo.", author: "Ludwig Wittgenstein", context: "Tractatus logico-philosophicus (1921), 5.6.", meaning: "Ampliar las palabras amplía lo que podemos pensar." },
  { text: "Yo soy yo y mi circunstancia, y si no la salvo a ella no me salvo yo.", author: "José Ortega y Gasset", context: "Meditaciones del Quijote (1914).", meaning: "Somos inseparables de nuestro contexto; cuidarlo es cuidarnos." },
  { text: "La vida solo puede ser comprendida mirando hacia atrás, pero ha de ser vivida mirando hacia adelante.", author: "Søren Kierkegaard", context: "Diarios (1843).", meaning: "El sentido aparece después; igual hay que avanzar." },
  { text: "Al hombre se le puede arrebatar todo salvo una cosa: la última de las libertades humanas, la elección de la actitud.", author: "Viktor Frankl", context: "El hombre en busca de sentido (1946), tras sobrevivir a los campos de concentración.", meaning: "Aun sin control de las circunstancias, conservamos la respuesta." },
  { text: "Entre el estímulo y la respuesta hay un espacio.", author: "Viktor Frankl", context: "Idea asociada a su obra, popularizada por Stephen Covey.", meaning: "En ese espacio está la libertad de elegir cómo responder." },

  // Oriente
  { text: "Un viaje de mil millas comienza con un solo paso.", author: "Lao-Tsé", context: "Tao Te Ching, capítulo 64.", meaning: "Lo enorme empieza siendo pequeño." },
  { text: "Quien conoce a los demás es sabio; quien se conoce a sí mismo es iluminado.", author: "Lao-Tsé", context: "Tao Te Ching, capítulo 33.", meaning: "El conocimiento más difícil es el de uno mismo." },
  { text: "La naturaleza no se apresura, y sin embargo todo se cumple.", author: "Lao-Tsé", context: "Idea del Tao Te Ching en versión popular.", meaning: "El ritmo sostenido logra más que la urgencia." },
  { text: "No importa lo despacio que vayas mientras no te detengas.", author: "Confucio", context: "Dicho atribuido en la tradición de las Analectas.", meaning: "La constancia vale más que la velocidad." },
  { text: "Elige un trabajo que ames y no tendrás que trabajar ni un día de tu vida.", author: "Confucio", context: "Atribución popular; no aparece literalmente en las Analectas.", meaning: "Cuando el trabajo tiene sentido, el esfuerzo pesa menos." },
  { text: "Aprender sin pensar es inútil; pensar sin aprender es peligroso.", author: "Confucio", context: "Analectas, libro II.", meaning: "Estudio y reflexión se necesitan mutuamente." },
  { text: "El que domina a los demás es fuerte; el que se domina a sí mismo es poderoso.", author: "Lao-Tsé", context: "Tao Te Ching, capítulo 33.", meaning: "El verdadero poder es el autodominio." },
  { text: "La mente lo es todo. Te conviertes en lo que piensas.", author: "Buda", context: "Paráfrasis popular del Dhammapada, verso 1.", meaning: "Los pensamientos repetidos moldean quiénes somos." },
  { text: "Aferrarse al enojo es como agarrar un carbón caliente para tirárselo a otro: el que se quema eres tú.", author: "Buda", context: "Paráfrasis moderna de la enseñanza de Buddhaghosa.", meaning: "El rencor daña primero a quien lo sostiene." },
  { text: "Cae siete veces, levántate ocho.", author: "Proverbio japonés", context: "Nana korobi ya oki.", meaning: "La resiliencia es levantarse una vez más de las que caemos." },
  { text: "Si tienes un problema que tiene solución, ¿para qué te preocupas? Y si no la tiene, ¿para qué te preocupas?", author: "Proverbio chino", context: "Atribuido también a Shantideva.", meaning: "La preocupación no ayuda en ningún caso: actuar o aceptar." },
  { text: "En la mente del principiante hay muchas posibilidades; en la del experto, pocas.", author: "Shunryu Suzuki", context: "Mente zen, mente de principiante (1970).", meaning: "Mirar con ojos nuevos abre caminos que la experiencia cierra." },

  // Literatura en español
  { text: "Siempre imaginé que el Paraíso sería algún tipo de biblioteca.", author: "Jorge Luis Borges", context: "Poema de los dones (1960).", meaning: "La lectura como lugar de plenitud." },
  { text: "He cometido el peor de los pecados que un hombre puede cometer. No he sido feliz.", author: "Jorge Luis Borges", context: "El remordimiento, en La moneda de hierro (1976).", meaning: "La felicidad también es una responsabilidad." },
  { text: "Uno no es lo que es por lo que escribe, sino por lo que ha leído.", author: "Jorge Luis Borges", context: "Frase de entrevistas; Borges se consideraba ante todo un lector.", meaning: "Lo que leemos nos forma." },
  { text: "Andábamos sin buscarnos, pero sabiendo que andábamos para encontrarnos.", author: "Julio Cortázar", context: "Rayuela (1963), capítulo 1.", meaning: "Algunos encuentros parecen casuales y a la vez inevitables." },
  { text: "Nada está perdido si se tiene el valor de proclamar que todo está perdido y hay que empezar de nuevo.", author: "Julio Cortázar", context: "Rayuela (1963).", meaning: "Aceptar el fracaso puede ser el primer paso para recomenzar." },
  { text: "La vida no es la que uno vivió, sino la que uno recuerda y cómo la recuerda para contarla.", author: "Gabriel García Márquez", context: "Epígrafe de Vivir para contarla (2002).", meaning: "La memoria y el relato dan forma a nuestra historia." },
  { text: "No hay medicina que cure lo que no cura la felicidad.", author: "Gabriel García Márquez", context: "Memoria de mis putas tristes (2004).", meaning: "La alegría también sana." },
  { text: "El secreto de una buena vejez no es otra cosa que un pacto honrado con la soledad.", author: "Gabriel García Márquez", context: "Cien años de soledad (1967).", meaning: "Hacer las paces con estar solo trae serenidad." },
  { text: "Caminante, son tus huellas el camino y nada más.", author: "Antonio Machado", context: "Campos de Castilla (1912), Proverbios y cantares XXIX.", meaning: "El camino no existe antes de recorrerlo." },
  { text: "Todo pasa y todo queda, pero lo nuestro es pasar.", author: "Antonio Machado", context: "Campos de Castilla (1912).", meaning: "Somos transitorios; lo importante es cómo pasamos." },
  { text: "Puedo escribir los versos más tristes esta noche.", author: "Pablo Neruda", context: "Poema 20, Veinte poemas de amor y una canción desesperada (1924).", meaning: "Escribir el dolor es una forma de atravesarlo." },
  { text: "Es tan corto el amor, y es tan largo el olvido.", author: "Pablo Neruda", context: "Poema 20 (1924).", meaning: "Lo intenso dura poco y su huella, mucho." },
  { text: "Podrán cortar todas las flores, pero no podrán detener la primavera.", author: "Pablo Neruda", context: "Frase atribuida; circula ligada a su obra política.", meaning: "Lo que nace con fuerza no se detiene por la fuerza." },
  { text: "La vida es sueño, y los sueños, sueños son.", author: "Pedro Calderón de la Barca", context: "La vida es sueño (1635), soliloquio de Segismundo.", meaning: "Relativizar lo que creemos real nos vuelve más humildes." },
  { text: "El que lee mucho y anda mucho, ve mucho y sabe mucho.", author: "Miguel de Cervantes", context: "Don Quijote de la Mancha, segunda parte (1615), cap. XXV.", meaning: "Leer y viajar ensanchan el mundo." },
  { text: "La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.", author: "Miguel de Cervantes", context: "Don Quijote, segunda parte, cap. LVIII.", meaning: "Pocas cosas valen tanto como ser libres." },
  { text: "Cada uno es artífice de su ventura.", author: "Miguel de Cervantes", context: "Don Quijote, segunda parte, cap. LXVI.", meaning: "Nuestra suerte depende en buena parte de nosotros." },
  { text: "Hay golpes en la vida, tan fuertes… ¡Yo no sé!", author: "César Vallejo", context: "Los heraldos negros (1918).", meaning: "Algunos dolores no tienen explicación, solo expresión." },
  { text: "Todo lo que se come sin necesidad se roba al estómago de los pobres.", author: "José Martí", context: "Pensamiento de sus escritos periodísticos.", meaning: "El exceso propio tiene un costo para otros." },
  { text: "Ser culto es el único modo de ser libre.", author: "José Martí", context: "Maestros ambulantes (1884).", meaning: "La educación es la base de la libertad." },
  { text: "Educar es depositar en cada hombre toda la obra humana que le ha antecedido.", author: "José Martí", context: "Escritos sobre educación.", meaning: "Aprender es heredar lo que otros construyeron." },
  { text: "Es mejor morir de pie que vivir de rodillas.", author: "Emiliano Zapata", context: "Frase atribuida; también usada por Dolores Ibárruri.", meaning: "La dignidad vale más que la comodidad." },
  { text: "Hay que endurecerse, pero sin perder la ternura jamás.", author: "Ernesto Guevara", context: "Frase atribuida, difundida en los años sesenta.", meaning: "La firmeza no tiene por qué borrar la sensibilidad." },
  { text: "Las palabras son como las monedas: una vale por muchas, como muchas no valen por una.", author: "Francisco de Quevedo", context: "Pensamiento de su obra moral (siglo XVII).", meaning: "Una palabra justa vale más que un discurso vacío." },
  { text: "Lo bueno, si breve, dos veces bueno.", author: "Baltasar Gracián", context: "Oráculo manual y arte de prudencia (1647), aforismo 105.", meaning: "La brevedad es una forma de respeto." },
  { text: "Saber y saberlo demostrar es valer dos veces.", author: "Baltasar Gracián", context: "Oráculo manual y arte de prudencia (1647).", meaning: "El conocimiento vale más cuando se comparte bien." },
  { text: "Soy de los que creen que la vida es un poco más amplia que los sueños.", author: "Mario Benedetti", context: "Pensamiento difundido de su obra.", meaning: "La realidad puede sorprender más que lo imaginado." },
  { text: "No te rindas, aún estás a tiempo de alcanzar y comenzar de nuevo.", author: "Mario Benedetti", context: "Atribuido a Benedetti; el poema circula con autoría discutida.", meaning: "Siempre queda margen para volver a empezar." },
  { text: "Lo peor no es cometer un error, sino tratar de justificarlo, en vez de aprovecharlo como aviso providencial de nuestra ligereza o ignorancia.", author: "Santiago Ramón y Cajal", context: "Reglas y consejos sobre investigación científica (1897).", meaning: "El error bien leído enseña; justificarlo lo desperdicia." },
  { text: "Todo hombre puede ser, si se lo propone, escultor de su propio cerebro.", author: "Santiago Ramón y Cajal", context: "Reglas y consejos sobre investigación científica (1897).", meaning: "La práctica cambia literalmente lo que somos capaces de hacer." },

  // Literatura universal
  { text: "Ser o no ser, esa es la cuestión.", author: "William Shakespeare", context: "Hamlet (c. 1600), acto III, escena 1.", meaning: "Las grandes preguntas sobre la existencia no se esquivan." },
  { text: "Somos de la misma materia de la que están hechos los sueños.", author: "William Shakespeare", context: "La tempestad (1611), acto IV.", meaning: "La vida tiene algo de efímero y de maravilloso." },
  { text: "Sé fiel a ti mismo.", author: "William Shakespeare", context: "Hamlet, acto I, escena 3: consejo de Polonio a Laertes.", meaning: "La coherencia con uno mismo sostiene el resto." },
  { text: "Todas las familias felices se parecen; cada familia desdichada lo es a su manera.", author: "León Tolstói", context: "Primera línea de Ana Karenina (1877).", meaning: "El sufrimiento tiene formas únicas; la armonía, rasgos comunes." },
  { text: "Todos piensan en cambiar el mundo, pero nadie piensa en cambiarse a sí mismo.", author: "León Tolstói", context: "Tres métodos de reforma (1900), paráfrasis.", meaning: "El cambio empieza por uno." },
  { text: "La belleza salvará al mundo.", author: "Fiódor Dostoievski", context: "El idiota (1869), dicho sobre el príncipe Myshkin.", meaning: "La belleza tiene una fuerza que redime." },
  { text: "Lo más importante es no mentirse a uno mismo.", author: "Fiódor Dostoievski", context: "Los hermanos Karamázov (1880), consejo del stárets Zósima.", meaning: "La honestidad empieza hacia adentro." },
  { text: "Un libro debe ser el hacha que rompa el mar helado dentro de nosotros.", author: "Franz Kafka", context: "Carta a Oskar Pollak (1904).", meaning: "La buena lectura nos sacude y nos transforma." },
  { text: "No es que sea tan inteligente, es que me quedo más tiempo con los problemas.", author: "Albert Einstein", context: "Frase atribuida, sin fuente documental clara.", meaning: "La perseverancia supera muchas veces al talento." },
  { text: "La imaginación es más importante que el conocimiento.", author: "Albert Einstein", context: "Entrevista en The Saturday Evening Post (1929).", meaning: "Imaginar abre lo que el saber todavía no alcanza." },
  { text: "La vida es como andar en bicicleta: para mantener el equilibrio hay que seguir moviéndose.", author: "Albert Einstein", context: "Carta a su hijo Eduard (1930).", meaning: "El movimiento constante da estabilidad." },
  { text: "Sé el cambio que quieres ver en el mundo.", author: "Mahatma Gandhi", context: "Paráfrasis popular de sus escritos (1913).", meaning: "Empezar por la propia conducta." },
  { text: "Vive como si fueras a morir mañana; aprende como si fueras a vivir siempre.", author: "Mahatma Gandhi", context: "Frase atribuida de sus enseñanzas.", meaning: "Urgencia para vivir, paciencia para aprender." },
  { text: "Parece imposible hasta que se hace.", author: "Nelson Mandela", context: "Frase atribuida, muy asociada a su figura.", meaning: "Lo imposible suele ser lo todavía no intentado." },
  { text: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", author: "Nelson Mandela", context: "Discurso en Johannesburgo (2003).", meaning: "Aprender transforma personas y sociedades." },
  { text: "No es la especie más fuerte la que sobrevive, sino la que mejor se adapta al cambio.", author: "Leon C. Megginson", context: "Paráfrasis de Darwin hecha por Megginson en 1963; suele atribuirse a Darwin.", meaning: "Adaptarse importa más que resistir." },
  { text: "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.", author: "Winston Churchill", context: "Atribución popular; su origen exacto es incierto.", meaning: "El entusiasmo sostiene el intento siguiente." },
  { text: "Nada en la vida debe ser temido, solo comprendido.", author: "Marie Curie", context: "Frase atribuida, difundida en biografías.", meaning: "Entender disuelve buena parte del miedo." },
  { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci", context: "Atribución popular.", meaning: "Llegar a lo simple requiere mucho trabajo." },
  { text: "El aprendizaje nunca agota la mente.", author: "Leonardo da Vinci", context: "Pensamiento de sus cuadernos (atribución).", meaning: "Aprender da energía en lugar de gastarla." },
  { text: "Quien mira hacia afuera, sueña; quien mira hacia adentro, despierta.", author: "Carl Jung", context: "Carta a Fanny Bowditch (1916).", meaning: "Conocerse es despertar." },
  { text: "Aquello a lo que te resistes, persiste.", author: "Carl Jung", context: "Paráfrasis popular de su pensamiento.", meaning: "Lo que evitamos mirar vuelve una y otra vez." },
  { text: "Uno no se da cuenta de lo que ha hecho, solo ve lo que queda por hacer.", author: "Marie Curie", context: "Carta a su hermano (1894).", meaning: "Conviene mirar también lo recorrido." },
  { text: "Escribo para saber lo que pienso.", author: "Joan Didion", context: "Why I Write (1976), retomando una idea de otros escritores.", meaning: "Escribir ordena y revela el pensamiento." },
  { text: "Cómo pasamos nuestros días es, por supuesto, cómo pasamos nuestras vidas.", author: "Annie Dillard", context: "The Writing Life (1989).", meaning: "La vida es la suma de los días comunes." },
  { text: "Dime, ¿qué planeas hacer con tu única, salvaje y preciosa vida?", author: "Mary Oliver", context: "The Summer Day (1990).", meaning: "La vida es una sola: vale preguntarse qué hacer con ella." },
  { text: "La atención es la forma más rara y pura de la generosidad.", author: "Simone Weil", context: "Carta a Joë Bousquet (1942).", meaning: "Prestar atención de verdad es un regalo." },
  { text: "Uno no nace mujer: llega a serlo.", author: "Simone de Beauvoir", context: "El segundo sexo (1949).", meaning: "Muchos roles se aprenden, no vienen dados." },
  { text: "No podemos elegir nuestras circunstancias externas, pero siempre podemos elegir cómo respondemos a ellas.", author: "Epicteto", context: "Paráfrasis moderna del Enquiridión.", meaning: "La respuesta es lo que nos pertenece." },
  { text: "Las personas olvidarán lo que dijiste, olvidarán lo que hiciste, pero nunca olvidarán cómo las hiciste sentir.", author: "Maya Angelou", context: "Frase atribuida, con antecedentes en Carl Buehner (1971).", meaning: "Lo que queda de un vínculo es cómo se sintió." },
  { text: "No hay mayor agonía que llevar dentro una historia no contada.", author: "Maya Angelou", context: "Yo sé por qué canta el pájaro enjaulado (1969).", meaning: "Contar lo propio libera." },
  { text: "Leer es soñar de la mano de otro.", author: "Fernando Pessoa", context: "Libro del desasosiego (póstumo, 1982).", meaning: "La lectura es un sueño compartido." },
  { text: "El poeta es un fingidor. Finge tan completamente que hasta finge que es dolor el dolor que de veras siente.", author: "Fernando Pessoa", context: "Autopsicografía (1932).", meaning: "El arte transforma la emoción real en otra cosa." },
  { text: "Lo que llamamos el principio es a menudo el final. Y hacer un final es hacer un principio.", author: "T. S. Eliot", context: "Little Gidding, Cuatro cuartetos (1942).", meaning: "Cada cierre abre algo nuevo." },
  { text: "La paciencia es el arte de esperar.", author: "Proverbio", context: "Refrán de uso común en español.", meaning: "Saber esperar también es hacer." },
  { text: "Quien madruga, Dios lo ayuda.", author: "Refrán español", context: "Refranero popular.", meaning: "Empezar temprano da ventaja." },
  { text: "Poco a poco se va lejos.", author: "Refrán español", context: "Refranero popular.", meaning: "La constancia lleva lejos." },
  { text: "No por mucho madrugar amanece más temprano.", author: "Refrán español", context: "Refranero popular.", meaning: "Hay procesos que no se pueden apurar." },

  // Ciencia, creatividad y trabajo
  { text: "La mejor manera de predecir el futuro es inventarlo.", author: "Alan Kay", context: "Reunión en Xerox PARC (1971).", meaning: "El futuro se construye, no solo se espera." },
  { text: "Si he visto más lejos es porque estoy sentado sobre hombros de gigantes.", author: "Isaac Newton", context: "Carta a Robert Hooke (1676).", meaning: "Todo logro se apoya en el trabajo de otros." },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein", context: "Atribución popular.", meaning: "Jugar también es una forma de pensar." },
  { text: "La inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso", context: "Frase atribuida en entrevistas.", meaning: "La constancia prepara el terreno para las buenas ideas." },
  { text: "Todo niño es un artista. El problema es cómo seguir siéndolo al crecer.", author: "Pablo Picasso", context: "Frase atribuida.", meaning: "Conservar la curiosidad es un desafío adulto." },
  { text: "El secreto de avanzar es empezar.", author: "Mark Twain", context: "Atribución popular.", meaning: "Arrancar destraba lo demás." },
  { text: "Dentro de veinte años estarás más decepcionado por las cosas que no hiciste que por las que hiciste.", author: "H. Jackson Brown Jr.", context: "P.S. I Love You (1990); suele atribuirse a Mark Twain.", meaning: "Arrepiente más lo no intentado." },
  { text: "Lo que se mide, mejora.", author: "Peter Drucker", context: "Idea asociada a su obra de gestión.", meaning: "Registrar algo lo vuelve visible y mejorable." },
  { text: "No hay nada tan inútil como hacer eficientemente lo que no debería hacerse.", author: "Peter Drucker", context: "Managing for Results (1964), idea central.", meaning: "Primero elegir qué hacer, después cómo." },
  { text: "Hecho es mejor que perfecto.", author: "Cultura de Facebook", context: "Lema que colgaba en carteles de las oficinas de la empresa.", meaning: "Terminar da más que perfeccionar sin fin." },
  { text: "La perfección no se alcanza cuando no hay nada más que añadir, sino cuando no hay nada más que quitar.", author: "Antoine de Saint-Exupéry", context: "Tierra de hombres (1939).", meaning: "Simplificar es refinar." },
  { text: "Solo se ve bien con el corazón.", author: "Antoine de Saint-Exupéry", context: "El principito (1943), capítulo XXI.", meaning: "La mirada afectiva descubre lo esencial." },
  { text: "Eres responsable para siempre de lo que has domesticado.", author: "Antoine de Saint-Exupéry", context: "El principito (1943), capítulo XXI.", meaning: "Los vínculos crean responsabilidad." },
  { text: "Si quieres construir un barco, no empieces por buscar madera, sino por despertar en los hombres el anhelo del mar.", author: "Antoine de Saint-Exupéry", context: "Atribución popular, inspirada en Ciudadela (1948).", meaning: "El deseo mueve más que las instrucciones." },
];
